[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paper-fetch"
version = "0.1.0"
description = "CLI tool to search AI research papers from arXiv"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "httpx",
    "typer",
    "arxiv"
]

[project.scripts]
paper-fetch = "paper_fetch.cli:app"

[tool.pytest.ini_options]
testpaths = ["testes"]